language: java
jdk:
  - oraclejdk8
script: mvn clean verify
before_script:
  - ssh-keygen -R soft.vub.ac.be
  - cp settings.xml ~/.m2/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_success: mvn install -P uploadRepo 
